---
title: "Wrap it up"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---

```{r setup, include=FALSE}
library(flexdashboard)
library(spotifyr)
library(tidyverse)
library(plotly)
library(ggrepel)
library(compmus)
```

```{r, results='hide'}
wrapped_2018 <- get_playlist_audio_features("", "15qQT7hCKC7xSsb43llL6P")
wrapped_2019 <- get_playlist_audio_features("", "2B1zQ9cHIIykfzNNPC0Qlp")
wrapped_2020 <- get_playlist_audio_features("", "1RaBvQSIMaFyQOnT1FJcEh")
wrapped_2021 <- get_playlist_audio_features("", "0aqaOBvRLmit3OHUYnoI19")
wrapped_2022 <- get_playlist_audio_features("", "5HuibSEuW4F0XV8bbwfboc")
wrapped_2023 <- get_playlist_audio_features("", "0KCCx3hblSejEcPh4kDoLR")

wrapped_full <-
  bind_rows(
    wrapped_2018 |> mutate(wrapped_year="2018"),
    wrapped_2019 |> mutate(wrapped_year="2019"),
    wrapped_2020 |> mutate(wrapped_year="2020"),
    wrapped_2021 |> mutate(wrapped_year="2021"),
    wrapped_2022 |> mutate(wrapped_year="2022"),
    wrapped_2023 |> mutate(wrapped_year="2023")
  )
```

```{css}
.chart-wrapper .chart-stage {
    overflow-y: auto;
    overflow-x: auto;
}
```

What a poser.
===================================== 

Wrapped Attributes {.tabset}
-------------------------------------
### Introduction 

When I was young, music didn’t really interest me. In fact, I despised most of the songs I heard on the radio. However, ever since I have been able to listen to music of my own choice (through Spotify, for example), it has become incredibly important to me. I have always tried to explore as much new music as possible since then, and I have always been interested in evolving my taste in music. So then, it’s only natural that I want to find out how my taste in music has changed over the years by studying the contents of each ’Spotify Wrapped’ playlist from 2018 onwards for this course.

For those who aren’t in the know, ’Spotify Wrapped’ is a gimmick developed by the streaming service that shows 100 of the tracks that a user has listened to the most in a particular year. Along with that, it shows the amount of minutes a user has spent listening to music on Spotify and some other fun facts about their listening behaviour. As Spotify is by far my most used medium for listening to music, I believe that each ’Wrapped’ playlist will be a good representative of my music taste.

When I first started using Spotify, I listened mostly to Hip-Hop and R&B, and I still do. However, over the years, I have also developed an interest for rock music (alternative and classic) and electronic music (a bit of a catch-all term, I know, but there is not a particular sub-genre I prefer). While I know how my taste has changed in terms of music genres, I’m excited to see the more specific information, measured by Spotify, but not necessarily shown publicly. I’ll provide the top track of my ’Wrapped’ playlist of each year since to provide a bit more insight:

2018: ’BagBak’ - Vince Staples 2019: ’Black Skinhead’ - Kanye West 2020: ’Astrothunder’ - Travis Scott 2021: ’Just’ - Radiohead 2022: ’Trippin on a Hole in a Paper Heart’ - Stone Temple Pilots 2023: ’The Appeal of Permanence’ - Reginald and Associates

In the first plot, you'll see some of the musical attributes from my 'Spotify Wrapped' from last year (2023). I have plotted acousticness, danceability, energy, liveness, speechiness, and valence. A similar plot will be very easy to make for the 'Spotify Wrapped' playlist of other years, so I can easily compare the attributes of songs in those playlists with eachother and with this one. I have also pointed out two noticeable outliers, namely "Fog (Again) - Live" by Radiohead in the liveness category and "DOGTOOTH" by Tyler, the Creator in the speechiness category.

This plot gives a good first look into the specifics of the music I listened to, but it is, of course, still a first draft.


### Wrapped 2023
    
```{r, results='hide'}
popularity <- wrapped_2023 %>%
  select(track.name, track.popularity,
         acousticness, danceability, energy, 
         liveness, speechiness, valence) %>%
  pivot_longer(cols = acousticness:valence,
               names_to = "attribute",
               values_to = "rating")

plot <- ggplot(popularity, aes(x = rating, y = track.popularity, colour = attribute)) +
  geom_point(alpha = 0.3, show.legend = FALSE) +
  geom_smooth(method = lm, formula = y~x, show.legend = FALSE) +
  facet_wrap(~attribute, scales = "free_x", nrow = 2) +
  labs(x = "Attribute Value",
       y = "Track Popularity") + 
  scale_color_brewer(palette="Dark2")

plot <- plot +
  geom_text(data = popularity %>% 
               filter(attribute == "liveness" & track.name == "Fog (Again) - Live"),
            aes(x = rating, y = track.popularity, label = track.name),
            vjust = -1, hjust = 1, size = 3, color = "black") +
  geom_text(data = popularity %>% 
               filter(attribute == "speechiness" & track.name == "DOGTOOTH"),
            aes(x = rating, y = track.popularity, label = track.name),
            vjust = -1, hjust = 1, size = 3, color = "black") + 
  geom_text(data = popularity %>% 
               filter(attribute == "speechiness" & track.name == "NIGHTMARE"),
            aes(x = rating, y = track.popularity, label = track.name),
            vjust = -1, hjust = 1, size = 3, color = "black") +
  geom_text(data = popularity %>% 
               filter(attribute == "valence" & track.name == "The Appeal of Permanence"),
            aes(x = rating, y = track.popularity, label = track.name),
            vjust = -1, hjust = 1, size = 3, color = "black")

plot
```

### Wrapped 2022
    
```{r, results='hide'}
popularity <- wrapped_2022 %>%
  select(track.name, track.popularity,
         acousticness, danceability, energy, 
         liveness, speechiness, valence) %>%
  pivot_longer(cols = acousticness:valence,
               names_to = "attribute",
               values_to = "rating")

plot <- ggplot(popularity, aes(x = rating, y = track.popularity, colour = attribute)) +
  geom_point(alpha = 0.3, show.legend = FALSE) +
  geom_smooth(method = lm, formula = y~x, show.legend = FALSE) +
  facet_wrap(~attribute, scales = "free_x", nrow = 2) +
  labs(x = "Attribute Value",
       y = "Track Popularity") + 
  scale_color_brewer(palette="Dark2") 

plot <- plot +
    geom_text(data = popularity %>% 
               filter(attribute == "speechiness" & track.name == "Tijdmachine"),
            aes(x = rating, y = track.popularity, label = track.name),
            vjust = -1, hjust = 1, size = 3, color = "black") +
      geom_text(data = popularity %>% 
               filter(attribute == "liveness" & track.name == "Interstate Love Song - Live 1994"),
            aes(x = rating, y = track.popularity, label = track.name),
            vjust = -1, hjust = 1, size = 3, color = "black") +
        geom_text(data = popularity %>% 
               filter(attribute == "danceability" & track.name == "This Must Be the Place (Naive Melody) - 2005 Remaster"),
            aes(x = rating, y = track.popularity, label = "This Must Be the Place"),
            vjust = -1, hjust = 1, size = 3, color = "black") +
        geom_text(data = popularity %>% 
               filter(attribute == "liveness" & track.name == "Go With The Flow"),
            aes(x = rating, y = track.popularity, label = track.name),
            vjust = -1, hjust = 1, size = 3, color = "black") 

plot
wrapped_2022
```

   
### Wrapped 2021

```{r, results='hide'}
popularity <- wrapped_2021 %>%
  select(track.name, track.popularity,
         acousticness, danceability, energy, 
         liveness, speechiness, valence) %>%
  pivot_longer(cols = acousticness:valence,
               names_to = "attribute",
               values_to = "rating")

plot <- ggplot(popularity, aes(x = rating, y = track.popularity, colour = attribute)) +
  geom_point(alpha = 0.3, show.legend = FALSE) +
  geom_smooth(method = lm, formula = y~x, show.legend = FALSE) +
  facet_wrap(~attribute, scales = "free_x", nrow = 2) +
  labs(x = "Attribute Value",
       y = "Track Popularity") + 
  scale_color_brewer(palette="Dark2")

plot
wrapped_2021
``` 
 
### Wrapped 2020
    
```{r, results='hide'}
popularity <- wrapped_2020 %>%
  select(track.name, track.popularity,
         acousticness, danceability, energy, 
         liveness, speechiness, valence) %>%
  pivot_longer(cols = acousticness:valence,
               names_to = "attribute",
               values_to = "rating")

plot <- ggplot(popularity, aes(x = rating, y = track.popularity, colour = attribute)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_smooth(method = lm, formula = y~x, show.legend = FALSE) +
  facet_wrap(~attribute, scales = "free_x", nrow = 2) +
  labs(x = "Attribute Value",
       y = "Track Popularity") + 
  scale_color_brewer(palette="Dark2")

plot
```

   
### Wrapped 2019

```{r, results='hide'}
popularity <- wrapped_2019 %>%
  select(track.name, track.popularity,
         acousticness, danceability, energy, 
         liveness, speechiness, valence) %>%
  pivot_longer(cols = acousticness:valence,
               names_to = "attribute",
               values_to = "rating")

plot <- ggplot(popularity, aes(x = rating, y = track.popularity, colour = attribute)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_smooth(method = lm, formula = y~x, show.legend = FALSE) +
  facet_wrap(~attribute, scales = "free_x", nrow = 2) +
  labs(x = "Attribute Value",
       y = "Track Popularity") + 
  scale_color_brewer(palette="Dark2")

plot
``` 
 
### Wrapped 2018
    
```{r, results='hide'}
popularity <- wrapped_2018 %>%
  select(track.name, track.popularity,
         acousticness, danceability, energy, 
         liveness, speechiness, valence) %>%
  pivot_longer(cols = acousticness:valence,
               names_to = "attribute",
               values_to = "rating")

plot <- ggplot(popularity, aes(x = rating, y = track.popularity, colour = attribute)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_smooth(method = lm, formula = y~x, show.legend = FALSE) +
  facet_wrap(~attribute, scales = "free_x", nrow = 2) +
  labs(x = "Attribute Value",
       y = "Track Popularity") + 
  scale_color_brewer(palette="Dark2")

plot
```

Interesting songs
=====================================


Wrapped Attributes {.tabset}
-------------------------------------
### Introduction 

On this page, I'll soon visualize the chromagrams of more songs. This is, however, still a rough draft. 

### Song 1: NIGHTMARE 

```{r}
NIGHTMARE <-
  get_tidy_audio_analysis("1yyLvWlI1qqvOkGRDUYE28") |>
  select(segments) |>
  unnest(segments) |>
  select(start, duration, pitches)

NIGHTMARE |>
  mutate(pitches = map(pitches, compmus_normalise, "euclidean")) |>
  compmus_gather_chroma() |> 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  ggtitle("Chromagram of NIGHTMARE by The Pillows") +
  theme_minimal() + 
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_viridis_c()
```
